image: maven:latest

stages:
    - build
    - test
    - deploy

#cache:
#    paths:
#        - .m2/repository/
#        - target/

build:
    stage: build
    script:
        - mvn compile
    artifacts:
        paths:
            -build/

test:
    stage: test
    script:
        - mvn test

#deploy:
#    stage: deploy
#    script:
#        - mvn deploy
#    only:
#        - master